
services:

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redash_init:
    image: redash/redash:10.1.0.b50633
    depends_on:
      - postgres
      - redis
    environment:
      REDASH_DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDASH_REDIS_URL: redis://redis:6379/0
      REDASH_COOKIE_SECRET: ${REDASH_COOKIE_SECRET}
    command: create_db

  server:
    image: redash/redash:10.1.0.b50633
    command: server
    depends_on:
      - redash_init
    ports:
      - "5000:5000"
    environment:
      REDASH_DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDASH_REDIS_URL: redis://redis:6379/0
      REDASH_COOKIE_SECRET: ${REDASH_COOKIE_SECRET}
    restart: always

  scheduler:
    image: redash/redash:10.1.0.b50633
    command: scheduler
    depends_on:
      - server
    environment:
      REDASH_DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDASH_REDIS_URL: redis://redis:6379/0
      REDASH_COOKIE_SECRET: ${REDASH_COOKIE_SECRET}
    restart: always

  worker:
    image: redash/redash:10.1.0.b50633
    command: worker
    depends_on:
      - server
    environment:
      REDASH_DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDASH_REDIS_URL: redis://redis:6379/0
      REDASH_COOKIE_SECRET: ${REDASH_COOKIE_SECRET}
    restart: always

  generator:
    build: ./generator
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    environment:
      POSTGRES_DB: ${ANALYTICS_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT:-5432}
      TOTAL_RECORDS: ${TOTAL_RECORDS}

volumes:
  postgres_data: